### ISSUE TITLE
unknown application vsc:bot_open_data

### ISSUE THREAD

**Issue by pidefrem** [theopenconversationkit/tock-bot-open-data#1]
Hello,

I'm trying to run the bot using the docker image

```
docker-compose -f docker-compose-bot-open-data.yml up
```

I'm getting this error:

```
bot_open_data_1  | 2017-05-31T08:37:09.037 [vert.x-worker-thread-0] DEBUG fr.vsct.tock.bot.engine.Nlp - Parse sentence : Hello [MessageWebhook(sender=Sender(id=xxxxx), recipient=Recipient(id=xxxxxx), timestamp=1496219826691, message=Message(mid='mid.$cAAEGwVijuwCA1cXaa5js-P3', seq=3144, text=Hello, attachments=[]))]
bot_open_data_1  | 2017-05-31T08:37:09.037 [vert.x-worker-thread-0] DEBUG fr.vsct.tock.bot.engine.Nlp - Sending sentence 'Hello' to NLP
bot_open_data_1  | May 31, 2017 8:37:09 AM okhttp3.internal.Platform log
bot_open_data_1  | INFO: --> POST http://nlp_api:8080/rest/nlp/parse http/1.1
bot_open_data_1  | May 31, 2017 8:37:09 AM okhttp3.internal.Platform log
bot_open_data_1  | INFO: Content-Type: application/json; charset=UTF-8
bot_open_data_1  | May 31, 2017 8:37:09 AM okhttp3.internal.Platform log
bot_open_data_1  | INFO: Content-Length: 353
bot_open_data_1  | May 31, 2017 8:37:09 AM okhttp3.internal.Platform log
bot_open_data_1  | INFO:
bot_open_data_1  | May 31, 2017 8:37:09 AM okhttp3.internal.Platform log
bot_open_data_1  | INFO: {"queries":["Hello"],"namespace":"vsc","applicationName":"bot_open_data","context":{"language":"es_ES","clientId":"xxxx","dialogId":"xxxxx","clientDevice":"messenger","referenceDate":"2017-05-31T10:37:09.038+02:00","referenceTimezone":"+02:00","engineType":{"name":"opennlp"},"registerQuery":true},"state":{"states":[]}}
bot_open_data_1  | May 31, 2017 8:37:09 AM okhttp3.internal.Platform log
bot_open_data_1  | INFO: --> END POST (353-byte body)
nlp_api_1        | 2017-05-31T08:37:09.771 [vert.x-worker-thread-0] ERROR fr.vsct.tock.nlp.api.NlpVerticle - unknown application vsc:bot_open_data
nlp_api_1        | java.lang.IllegalStateException: unknown application vsc:bot_open_data
nlp_api_1        |      at fr.vsct.tock.nlp.front.service.ParserService.parse(ParserService.kt:74)
nlp_api_1        |      at fr.vsct.tock.nlp.front.client.FrontClient.parse(FrontClient.kt)
nlp_api_1        |      at fr.vsct.tock.nlp.api.NlpVerticle$configure$$inlined$blockingJsonPost$1.invoke(WebVerticle.kt:330)
nlp_api_1        |      at fr.vsct.tock.nlp.api.NlpVerticle$configure$$inlined$blockingJsonPost$1.invoke(WebVerticle.kt:56)
nlp_api_1        |      at fr.vsct.tock.shared.vertx.WebVerticle$blocking$1.handle(WebVerticle.kt:192)
nlp_api_1        |      at fr.vsct.tock.shared.vertx.WebVerticle$blocking$1.handle(WebVerticle.kt:56)
nlp_api_1        |      at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
nlp_api_1        |      at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:271)
nlp_api_1        |      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
nlp_api_1        |      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
nlp_api_1        |      at java.lang.Thread.run(Thread.java:745)
nlp_api_1        | May 31, 2017 8:37:09 AM io.vertx.ext.web.impl.RoutingContextImplBase
nlp_api_1        | SEVERE: Unexpected exception in route
nlp_api_1        | java.lang.IllegalStateException: unknown application vsc:bot_open_data
nlp_api_1        |      at fr.vsct.tock.nlp.front.service.ParserService.parse(ParserService.kt:74)
nlp_api_1        |      at fr.vsct.tock.nlp.front.client.FrontClient.parse(FrontClient.kt)
nlp_api_1        |      at fr.vsct.tock.nlp.api.NlpVerticle$configure$$inlined$blockingJsonPost$1.invoke(WebVerticle.kt:330)
nlp_api_1        |      at fr.vsct.tock.nlp.api.NlpVerticle$configure$$inlined$blockingJsonPost$1.invoke(WebVerticle.kt:56)
nlp_api_1        |      at fr.vsct.tock.shared.vertx.WebVerticle$blocking$1.handle(WebVerticle.kt:192)
nlp_api_1        |      at fr.vsct.tock.shared.vertx.WebVerticle$blocking$1.handle(WebVerticle.kt:56)
nlp_api_1        |      at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
nlp_api_1        |      at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:271)
nlp_api_1        |      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
nlp_api_1        |      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
nlp_api_1        |      at java.lang.Thread.run(Thread.java:745)
nlp_api_1        |
```

In my messenger page I get the generic error message: 'Sorry, I didn't understand 😞'

Do you have any idea where this could come from?

Thanks in advance for your help.

**Comment by vsct-jburet** [comment]
There was no nlp application included in the source code. 

With the commit https://github.com/voyages-sncf-technologies/tock-bot-open-data/commit/1da8dfc8e6fdbb150f11fd7a6b78b665cc47b886, there is now one.

So if you pull the last docker images: 
`docker-compose -f docker-compose-bot-open-data.yml pull`
and restart the bot, it will work.

Please note that it is a very small model, not very accurate. But it's a good start :) 

Dialog sample:

![recherche](https://cloud.githubusercontent.com/assets/12413454/26655303/912e1e84-465a-11e7-9f87-d613f779595d.png)
![recherche2](https://cloud.githubusercontent.com/assets/12413454/26655309/96ee8764-465a-11e7-9882-a9c61157420a.png)
