### ISSUE TITLE
ERROR at UserTimelineMongoDAO

### ISSUE THREAD

**Issue by ddebarbieux** [theopenconversationkit/tock-bot-open-data#5]
The full stack trace:

```
bot_open_data_1    | 2018-08-31T09:18:16.159 [vert.x-worker-thread-6] DEBUG fr.vsct.tock.bot.connector.ga.GAConnector - Google Assistant request input : {"user":{"userId":"ABwppHHMZ0a1rS_pJWI6PX8gu4855h6_T0znqwVxazqMlPIAlL0YFQMsY67yqY59UTZWBb2-0ztSAQ","locale":"fr-FR","lastSeen":"2018-08-31T09:16:33Z"},"conversation":{"conversationId":"ABwppHGzgc9KiqRYV8nYSFMfq-3PqNygqMhPmlmGXq-qCgNA7C8Ys2pSTrWxZNNvsHWufgAtkM7oxA","type":"NEW"},"inputs":[{"intent":"actions.intent.TEXT","rawInputs":[{"inputType":"KEYBOARD","query":"today"}],"arguments":[{"name":"text","rawText":"today","textValue":"today"}]}],"surface":{"capabilities":[{"name":"actions.capability.SCREEN_OUTPUT"},{"name":"actions.capability.AUDIO_OUTPUT"},{"name":"actions.capability.WEB_BROWSER"},{"name":"actions.capability.MEDIA_RESPONSE_AUDIO"}]},"isInSandbox":true,"requestType":"SIMULATOR"}
bot_open_data_1    | 2018-08-31T09:18:16.159 [vert.x-worker-thread-6] DEBUG fr.vsct.tock.bot.definition.EventListenerBase - listen event today
bot_open_data_1    | 2018-08-31T09:18:16.160 [vert.x-worker-thread-6] DEBUG fr.vsct.tock.bot.engine.TockConnectorController - try to lock PlayerId(id=ABwppHHMZ0a1rS_pJWI6PX8gu4855h6_T0znqwVxazqMlPIAlL0YFQMsY67yqY59UTZWBb2-0ztSAQ, type=user, clientId=null)
bot_open_data_1    | 2018-08-31T09:18:16.161 [vert.x-worker-thread-6] DEBUG fr.vsct.tock.bot.mongo.MongoUserLock - lock user : ABwppHHMZ0a1rS_pJWI6PX8gu4855h6_T0znqwVxazqMlPIAlL0YFQMsY67yqY59UTZWBb2-0ztSAQ
bot_open_data_1    | 2018-08-31T09:18:16.165 [vert.x-worker-thread-6] ERROR fr.vsct.tock.bot.mongo.UserTimelineMongoDAO - Instantiation of [simple type, class fr.vsct.tock.bot.open.data.client.sncf.model.SncfPlace] value failed for JSON property embedded_type due to missing (therefore NULL) value for creator parameter embeddedType which is a non-nullable type
bot_open_data_1    |  at [Source: de.undercouch.bson4jackson.io.LittleEndianInputStream@3935668e; pos: 607] (through reference chain: fr.vsct.tock.bot.mongo.DialogCol["state"]->fr.vsct.tock.bot.mongo.DialogCol$DialogStateMongoWrapper["entityValues"]->java.util.LinkedHashMap["origin"]->fr.vsct.tock.bot.mongo.DialogCol$EntityStateValueWrapper["value"]->fr.vsct.tock.bot.engine.dialog.EntityValue["value"]->fr.vsct.tock.bot.open.data.client.sncf.model.SncfPlace["embedded_type"])
bot_open_data_1    | com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class fr.vsct.tock.bot.open.data.client.sncf.model.SncfPlace] value failed for JSON property embedded_type due to missing (therefore NULL) value for creator parameter embeddedType which is a non-nullable type
bot_open_data_1    |  at [Source: de.undercouch.bson4jackson.io.LittleEndianInputStream@3935668e; pos: 607] (through reference chain: fr.vsct.tock.bot.mongo.DialogCol["state"]->fr.vsct.tock.bot.mongo.DialogCol$DialogStateMongoWrapper["entityValues"]->java.util.LinkedHashMap["origin"]->fr.vsct.tock.bot.mongo.DialogCol$EntityStateValueWrapper["value"]->fr.vsct.tock.bot.engine.dialog.EntityValue["value"]->fr.vsct.tock.bot.open.data.client.sncf.model.SncfPlace["embedded_type"])
bot_open_data_1    | 	at com.fasterxml.jackson.module.kotlin.KotlinValueInstantiator.createFromObjectWith(KotlinValueInstantiator.kt:53)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:189)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:487)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1265)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:325)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:194)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1261)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:325)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:194)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:130)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:254)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:517)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:527)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:416)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1265)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:325)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:519)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:527)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:416)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1265)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:325)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:527)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:519)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:527)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:416)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1265)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:325)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:519)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:527)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:416)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1265)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:325)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
bot_open_data_1    | 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3079)
bot_open_data_1    | 	at org.litote.kmongo.jackson.JacksonCodec.decode(JacksonCodec.kt:164)
bot_open_data_1    | 	at com.mongodb.operation.CommandResultArrayCodec.decode(CommandResultArrayCodec.java:52)
bot_open_data_1    | 	at com.mongodb.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:60)
bot_open_data_1    | 	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:84)
bot_open_data_1    | 	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:41)
bot_open_data_1    | 	at org.bson.codecs.configuration.LazyCodec.decode(LazyCodec.java:47)
bot_open_data_1    | 	at org.bson.codecs.BsonDocumentCodec.readValue(BsonDocumentCodec.java:101)
bot_open_data_1    | 	at com.mongodb.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:63)
bot_open_data_1    | 	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:84)
bot_open_data_1    | 	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:41)
bot_open_data_1    | 	at com.mongodb.internal.connection.ReplyMessage.<init>(ReplyMessage.java:48)
bot_open_data_1    | 	at com.mongodb.internal.connection.InternalStreamConnection.getCommandResult(InternalStreamConnection.java:393)
bot_open_data_1    | 	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:299)
bot_open_data_1    | 	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:255)
bot_open_data_1    | 	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:99)
bot_open_data_1    | 	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:444)
bot_open_data_1    | 	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:72)
bot_open_data_1    | 	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:200)
bot_open_data_1    | 	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:269)
bot_open_data_1    | 	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:131)
bot_open_data_1    | 	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:123)
bot_open_data_1    | 	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:242)
bot_open_data_1    | 	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:233)
bot_open_data_1    | 	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:136)
bot_open_data_1    | 	at com.mongodb.operation.AggregateOperationImpl$1.call(AggregateOperationImpl.java:193)
bot_open_data_1    | 	at com.mongodb.operation.AggregateOperationImpl$1.call(AggregateOperationImpl.java:189)
bot_open_data_1    | 	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:457)
bot_open_data_1    | 	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:401)
bot_open_data_1    | 	at com.mongodb.operation.AggregateOperationImpl.execute(AggregateOperationImpl.java:189)
bot_open_data_1    | 	at com.mongodb.operation.AggregateOperation.execute(AggregateOperation.java:294)
bot_open_data_1    | 	at com.mongodb.operation.AggregateOperation.execute(AggregateOperation.java:41)
bot_open_data_1    | 	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:179)
bot_open_data_1    | 	at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:132)
bot_open_data_1    | 	at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:86)
bot_open_data_1    | 	at com.mongodb.client.internal.MongoIterableImpl.first(MongoIterableImpl.java:92)
bot_open_data_1    | 	at kotlin.collections.KMongoIterableKt.firstOrNull(KMongoIterable.kt:67)
bot_open_data_1    | 	at fr.vsct.tock.bot.mongo.UserTimelineMongoDAO.loadLastValidDialogCol(UserTimelineMongoDAO.kt:376)
bot_open_data_1    | 	at fr.vsct.tock.bot.mongo.UserTimelineMongoDAO.loadLastValidDialog(UserTimelineMongoDAO.kt:381)
bot_open_data_1    | 	at fr.vsct.tock.bot.mongo.UserTimelineMongoDAO.loadWithLastValidDialog(UserTimelineMongoDAO.kt:313)
bot_open_data_1    | 	at fr.vsct.tock.bot.engine.TockConnectorController.handleAction(TockConnectorController.kt:104)
bot_open_data_1    | 	at fr.vsct.tock.bot.engine.TockConnectorController.handle(TockConnectorController.kt:82)
bot_open_data_1    | 	at fr.vsct.tock.bot.connector.ga.GAConnector.handleRequest$tock_bot_connector_ga(GAConnector.kt:91)
bot_open_data_1    | 	at fr.vsct.tock.bot.connector.ga.GAConnector$register$1$1$1.invoke(GAConnector.kt:68)
bot_open_data_1    | 	at fr.vsct.tock.bot.connector.ga.GAConnector$register$1$1$1.invoke(GAConnector.kt:46)
bot_open_data_1    | 	at fr.vsct.tock.shared.vertx.VertXsKt$vertxExecutor$1.invoke(VertXs.kt:149)
bot_open_data_1    | 	at fr.vsct.tock.shared.vertx.VertXsKt$vertxExecutor$1.access$invoke(VertXs.kt:107)
bot_open_data_1    | 	at fr.vsct.tock.shared.vertx.VertXsKt$vertxExecutor$1$executeBlocking$2.invoke(VertXs.kt:121)
bot_open_data_1    | 	at fr.vsct.tock.shared.vertx.VertXsKt$vertxExecutor$1$executeBlocking$2.invoke(VertXs.kt:107)
bot_open_data_1    | 	at fr.vsct.tock.shared.vertx.VertXsKt$blocking$1.handle(VertXs.kt:73)
bot_open_data_1    | 	at fr.vsct.tock.shared.vertx.VertXsKt$blocking$1.handle(VertXs.kt)
bot_open_data_1    | 	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:273)
bot_open_data_1    | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
bot_open_data_1    | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
bot_open_data_1    | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
bot_open_data_1    | 	at java.base/java.lang.Thread.run(Thread.java:844)

```

**Comment by vsct-jburet** [comment]
Thanks for reporting

To check the fix I'm going to commit, you will need to pull the last docker version (go the tock-docker project edit .env file with TAG=1.2.1-SNAPSHOT and docker pull

An other option is to run the bot open data project in the IDE
